//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ChiTietHoaDonDichVu
    {
        [DisplayName("Number Of Services")]
        public byte SoLuong { get; set; }
        [DisplayName("Invoice Code")]
        public string MaHoaDon { get; set; }
        [DisplayName("Service Code")]
        public string MaDichVu { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
