//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LoaiPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiPhong()
        {
            this.Phongs = new HashSet<Phong>();
        }

        [DisplayName("Room Category Code")]
        [Required(ErrorMessage = "Mã loại phòng không được để trống.")]
        public string MaLoaiPhong { get; set; }

        [DisplayName("Room Category Name")]
        [Required(ErrorMessage = "Tên loại phòng không được để trống.")]
        public string TenLoaiPhong { get; set; }
        [DisplayName("Room Rates")]
        [Required(ErrorMessage = "Giá loại phòng không được để trống.")]
        public decimal GiaLoaiPhong { get; set; }
        [DisplayName("Room Category Images")]
        public string HinhAnh { get; set; }
        [DisplayName("Capacity")]
        [Required(ErrorMessage = "Số người tối đa không được để trống.")]
        public byte SoNguoiToiDa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
