//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        
        public NhanVien()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.TaiKhoanNVs = new HashSet<TaiKhoanNV>();
        }

        [DisplayName("Staff ID")]
        public int MaNhanVien { get; set; }
        [DisplayName("ID Number")]
        [Required(ErrorMessage = "CCCD không được bỏ trống")]
        public string CCCD { get; set; }
        [DisplayName("Phone Number")]
        [Required(ErrorMessage = "Số điện thoại không được bỏ trống")]
        public string SoDienThoai { get; set; }
        [DisplayName("Staff Name")]
        [Required(ErrorMessage = "Tên nhân viên không được bỏ trống")]
        public string TenNhanVien { get; set; }
        [DisplayName("Date Of Birth")]
        [DataType(DataType.Date, ErrorMessage = "Date only")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Ngày sinh nhân viên chưa được chọn.")]
        [CustomValidation(typeof(NhanVien), "ValidateDateOfBirth")]
        public System.DateTime? NgaySinh { get; set; }
        [DisplayName("Job Title")]
        public string ChucDanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiKhoanNV> TaiKhoanNVs { get; set; }
        public static ValidationResult ValidateDateOfBirth(DateTime? ngaySinh, ValidationContext context)
        {
            if (ngaySinh.HasValue)
            {
                DateTime currentDate = DateTime.Now;

                // Tính toán số tuổi
                int age = currentDate.Year - ngaySinh.Value.Year;

                // Kiểm tra nếu ngày sinh sau ngày hiện tại thì giảm tuổi đi 1
                if (ngaySinh.Value.Date > currentDate.Date)
                {
                    age--;
                }

                // Kiểm tra nếu tuổi nhỏ hơn 18
                if (age < 18)
                {
                    return new ValidationResult("Nhân viên phải đủ 18 tuổi trở lên.");
                }
            }

            return ValidationResult.Success;
        }
    }
}
