//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TaiKhoanKH
    {
        [EmailAddress(ErrorMessage = "Vui lòng nhập Email")]
        [DisplayName("Email")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string TenTaiKhoan { get; set; }

        [StringLength(100, ErrorMessage = "Mật khẩu phải tối thiểu 6 ký tự", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [DisplayName("Password")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string MatKhau { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("MatKhau", ErrorMessage = "Mật khẩu xác nhận không chính xác")]
        public string ConfirmPassword { get; set; }
        public Nullable<int> MaKhachHang { get; set; }

        public virtual KhachHang KhachHang { get; set; }
    }
}
